#-------------------------------
# General Site Settings
title: M4lcode
#logo: '/images/logo.jpg'
baseurl: "" # The subpath of your site, e.g. /blog
url: "https://m4lcode.github.io"
#-------------------------------
# Build settings
markdown: kramdown
permalink: /:title
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-feed

paginate: 8
paginate_path: "/page/:num"

# Pages Path
defaults:
  - scope:
      path: '_pages'
    values:
      permalink: /:basename:output_ext

include:
  - _pages

sass:
  sass_dir: _sass
  style: compressed